name: backend
description: Servidor Backend usando Dart e Shelf.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
